import { poppins } from "@/helpers/fonts";
import type { Metadata } from "next";
import "@/styles/index.scss"

export const metadata: Metadata = {
  title: "SmyrnaEdu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={poppins.variable}>
      <body>
        <p>Merhab Dünya</p>
        {children}
      </body>
    </html>
  );
}
